controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: forward_command_controller/ForwardCommandController

    velocity_controller:
      type: forward_command_controller/ForwardCommandController

position_controller:
  ros__parameters:
    joints:
      - servo_joint_1
      - servo_joint_2
      - servo_joint_4
      - servo_joint_5
      - servo_joint_7
      - servo_joint_8
      - servo_joint_10
      - servo_joint_11
    interface_name: position

velocity_controller:
  ros__parameters:
    joints:
      - servo_joint_3
      - servo_joint_6
      - servo_joint_9
      - servo_joint_12
    interface_name: velocity
