st3215_service_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    # servo_ids: [10,12]
    # position_servo_ids: [10]
    # velocity_servo_ids: [12]
    servo_ids: [1,2,3,4,5,6,7,8,9,10,11,12]
    position_servo_ids: [1,2,4,5,7,8,10,11]
    velocity_servo_ids: [3,6,9,12]
    # Per-servo position limits in ticks [min, max] (0-4095).
    # Servo 13 has physical limit around 2048-2500
  
