controller_manager:
  ros__parameters:
    update_rate: 50  # Hz 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - servo_joint_1
      - servo_joint_2
      - servo_joint_3
      - servo_joint_4
      - servo_joint_5
      - servo_joint_6
      - servo_joint_7
      - servo_joint_8
      - servo_joint_9
      - servo_joint_10
      - servo_joint_11
      - servo_joint_12

joint_trajectory_controller:
  ros__parameters:
    joints:
      - servo_joint_1
      - servo_joint_2
      - servo_joint_3
      - servo_joint_4
      - servo_joint_5
      - servo_joint_6
      - servo_joint_7
      - servo_joint_8
      - servo_joint_9
      - servo_joint_10
      - servo_joint_11
      - servo_joint_12

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # 200
    action_monitor_rate: 20.0 # 100

    allow_partial_joints_goal: true
    open_loop_control: false
    allow_integration_in_goal_trajectories: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
